server {
    listen 443 ssl;

    server_name gapi.xhproxy.org;  # 替换为你的域名或IP地址

    # 引入共享的 SSL 配置
    include conf.d/ssl_params.conf;

    include conf.d/dns_common.conf;

    include conf.d/proxy_params.conf;

    location / {
        # 将请求代理到 Google API
        proxy_pass https://generativelanguage.googleapis.com;

        # 重写 Host 头，使其与目标服务器匹配
        proxy_set_header Host generativelanguage.googleapis.com;
    }
}
