#!/usr/bin/env bash

export MYSQL_HOST=127.0.0.1
export MYSQL_PORT=3306
export MYSQL_ROOT_USER=root
export MYSQL_ROOT_PASSWORD=123456

export MYSQL_NACOS_DB=nacos
export MYSQL_NACOS_USER=nacos
export MYSQL_NACOS_PASSWORD=nacos

export NACOS_VERSION=3.1.1
export NACOS_IMAGE=nacos/nacos-server:v${NACOS_VERSION}
export NACOS_MYSQL_SCHEMA_URL=https://raw.githubusercontent.com/alibaba/nacos/${NACOS_VERSION}/distribution/conf/mysql-schema.sql
export NACOS_MYSQL_SCHEMA_FILE=/tmp/mysql-schema-${NACOS_VERSION}.sql

#创建数据库和用户
mysql -h${MYSQL_HOST} -P${MYSQL_PORT} -u${MYSQL_ROOT_USER} -p${MYSQL_ROOT_PASSWORD} <<EOF
CREATE DATABASE IF NOT EXISTS ${MYSQL_NACOS_DB} DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE USER IF NOT EXISTS '${MYSQL_NACOS_USER}'@'%' IDENTIFIED BY '${MYSQL_NACOS_PASSWORD}';
GRANT ALL PRIVILEGES ON ${MYSQL_NACOS_DB}.* TO '${MYSQL_NACOS_USER}'@'%';
FLUSH PRIVILEGES;
EOF

#导入 Nacos 表结构
wget -q -O ${NACOS_MYSQL_SCHEMA_FILE} ${NACOS_MYSQL_SCHEMA_URL}
mysql -h${MYSQL_HOST} -P${MYSQL_PORT} -u${MYSQL_NACOS_USER} -p${MYSQL_NACOS_PASSWORD} ${MYSQL_NACOS_DB} < ${NACOS_MYSQL_SCHEMA_FILE}

