# REST API 偶尔会 POST JSON / Multipart
client_max_body_size 120m;

# 快速发现后端机器不可连接
proxy_connect_timeout 3s;

# 普通 REST 请求
proxy_send_timeout 60s;
proxy_read_timeout 60s;

# API 推荐保持 buffering
proxy_request_buffering on;
proxy_buffering on;

# 后端故障时尝试其它实例
proxy_next_upstream error timeout http_502 http_503 http_504;
proxy_next_upstream_tries 2;
