# 允许上传超大文件
client_max_body_size 100g;

# 大文件上传增大超时
client_body_timeout 600s;

# 大文件下载给客户端
send_timeout 600s;

# 后端处理上传/下载可能时间很长
proxy_send_timeout 600s;
proxy_read_timeout 600s;

# 大文件直接流向后端
proxy_request_buffering off;

# 下载直接向客户端流式发送
proxy_buffering off;