
# 不需要上传
client_max_body_size 1m;

# 静态资源大量打开文件
open_file_cache max=10000 inactive=120s;
open_file_cache_valid 120s;
open_file_cache_min_uses 2;
open_file_cache_errors off;

sendfile on;
tcp_nopush on;

# 文本资源压缩
gzip on;
gzip_comp_level 5;
gzip_min_length 1024;

gzip_types
    text/plain
    text/css
    application/javascript
    application/json
    application/xml
    image/svg+xml;
